### PR TITLE
baseURL typo

### PR DESCRIPTION
**Pull request by rico542**

### CODE REVIEW

**Comment by rico542** [comment]
Thanks for your work.
It helped us.

**Comment by vaga** [comment]
It's not a typo.

If I put `baseURL`, an error is occured:
```
ERROR 2021/01/13 15:28:19 render of "page" failed: execute of template failed: template: _default/single.html:21:23: executing "_default/single.html" at <.Site.baseURL>: can't evaluate field baseURL in type page.Site
```

**Comment by rico542** [comment]
> It's not a typo.
> 
> If I put `baseURL`, an error is occured:
> 
> ```
> ERROR 2021/01/13 15:28:19 render of "page" failed: execute of template failed: template: _default/single.html:21:23: executing "_default/single.html" at <.Site.baseURL>: can't evaluate field baseURL in type page.Site
> ```
> 
> See docs: https://gohugo.io/variables/site/#site-variables-list

Ok
I see, i tried and i have the same issue, except in [Params], maybe a different case sensitivity.
Anyway thanks and sorry for the fake patch.

**Comment by vaga** [comment]
`.Site.Params` is a map and we can access to field names without an upper case letter.

```
- The name of a key of the data, which must be a map, preceded
  by a period, such as
	.Key
  The result is the map element value indexed by the key.
  Key invocations may be chained and combined with fields to any
  depth:
    .Field1.Key1.Field2.Key2
  Although the key must be an alphanumeric identifier, unlike with
  field names they do not need to start with an upper case letter.
  Keys can also be evaluated on variables, including chaining:
    $x.key1.key2
```
https://golang.org/pkg/text/template/#hdr-Arguments

**Comment by rico542** [comment]
Thanks for explanations,

Your m10c is a great job, we're proud to tell you we're using it on [Mobian's blog](https://blog.mobian-project.org/), it's exactly what we were looking for.
Of course sources referenced your work, they're not public yet (we need to make the theme and publications as sub-modules) but i'll tell you as soon as they gonna be public.

A bientôt sur la toile ! (*)

(*) See you soon on the Web !

**Pull request closed without merging**
