### PR TITLE
Add explicit avatar height/width

### PR DESCRIPTION
**Pull request by squalrus**
Seeing a few issues in [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsqualr.us%2F&tab=mobile&hl=en) related to the avatar image size not being set and content shifting. Thoughts on the proposed changes?

image

image

### CODE REVIEW

**Review by vaga — CHANGES_REQUESTED** [review]
If you define the width/height in HTML element, we can remove max-width and max-height in CSS file.
I don't understand why it doesn't take CSS properties. If you have an explanation, let me know.

**Comment by squalrus** [comment]
> I don't understand why it doesn't take CSS properties. If you have an explanation, let me know.

I believe a CSS-only solution would be acceptable, but would have to be updated to `height` and `width`, rather than `max-height` and `max-width`. Currently the text could appear before the image causing the Cumulative Layout Shift to occur when the image "pops" in.

I think the foolproof solution, and part of [Google's AMP](https://developers.google.com/amp/) initiative, is to add the `height` and `width` to the images themselves (assuming the size does not change via CSS).

Let me know how you'd like to proceed and I can update the pull request!

**Comment by vaga** [comment]
I prefer to remove max- prefix if it works, my next issue is to rework the header for better mobile header. (#61)

**Comment by squalrus** [comment]
@vaga updated! Let me know what you think.

**Comment by squalrus** [comment]
Hey @vaga! Wanted to follow-up on this after rolling out the latest changes. I'm now seeing [100% for my site](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsqualr.us%2F) and the Cumulative Layout Shift is no longer an issue thanks to the CSS update.

image

Thanks again for the awesome, performant theme!

**Pull request merged**
